name: Run Scraper

on:
  schedule:
    - cron: '37 2,10,18 * * *'
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: '**/requirements.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Fetch old data from gh-pages
        run: |
          git fetch origin gh-pages || true
          git show origin/gh-pages:announcements.json > announcements.json || true

      - name: Run python script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python scraper.py

      - name: Commit and Push to gh-pages
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          cp announcements.json /tmp/announcements.json
          
          git checkout -- announcements.json || true
          
          git fetch origin gh-pages
          git checkout gh-pages
          
          cp /tmp/announcements.json announcements.json
          
          git add announcements.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto update: sync data to gh-pages" && git push origin gh-pages)
